### ISSUE TITLE
Publish to Terraform Registry?

### ISSUE THREAD

**Issue by M1kep** [appgate/terraform-provider-appgate-sdp#104]
Are there any plans or something blocking this provider from being added to the Terraform Registry? This would allow much easier usage.

**Comment by danijeel** [comment]
Hi @M1kep , yes I agree. We have been trying to, but hashicorp has not replied to our support ticket regarding this case. Its still work in progress, I will reply here once I know more.

**Comment by danijeel** [comment]
We managed to publish it now, its available at  https://registry.terraform.io/providers/appgate/appgate-sdp/latest


```hcl
terraform {
  required_providers {
    appgate-sdp = {
      source = "appgate/appgate-sdp"
      version = "0.4.0"
    }
  }
}

provider "appgate-sdp" {
  # Configuration options
}
```
