### ISSUE TITLE
renaming repo in standard terraform-provider-appgate format

### ISSUE THREAD

**Issue by stephengroat-dd** [appgate/terraform-provider-appgate-sdp#91]
just started using the new terraform provider and so far, it's working well!

when getting the provider setup, the lack of follow the terraform convention of `terraform-provider-[PROVIDER_NAME]` format has become somewhat of an issue. we use the `terraform.d/plugins` directory to use repo-stored copies of the provider. since the repo is named `sdp-terraform-provider`, `goreleaser` is creating zips in the same format. since the only acceptable format for terraform 14+ is `terraform-provider-TYPE_VERSION_TARGET.zip` (as well as the binary inside of `terraform-provider-TYPE_VERSION`, it causes us to have to rename the binaries before use

could the repo be renamed to follow the terraform naming convention and release zips in the conventional format so they can be used without modification?

**Comment by danijeel** [comment]
Hey @stephengroat-dd, yes this make sense. I've updated the repo name and included a new release with the correct name in the binaries.

**Comment by stephengroat-dd** [comment]
seems to be working great thanks!
