### ISSUE TITLE
Incorrect seed version

### ISSUE THREAD

**Issue by hobietje** [appgate/terraform-provider-appgate-sdp#93]
The seed files generated by the "appgate_appliance_seed" data source are not accepted by our cz-config.  Regardless of the "latest_version" flag, we seem to get version 13 provided by the TF provider.  We receive the error "WARNING [seeding] Invalid seed config: Invalid seed configuration, expected Optional[Remote] at remote but got dict..." when trying to use them as the seed. 

A manually exported seed file using the "latest_version" flag works fine, and provides a version 14 seed file.

**Comment by danijeel** [comment]
Hi, What versions are you using for
- appliance
- terraform
- terraform-provider-appgate-sdp

**Comment by hobietje** [comment]
Hi @danijeel 

appliances are the AWS BYOL AMI: 5.3.2-23587-release
terraform-provider-appgate-sdp: 0.3.5
terraform: v0.14.4

**Comment by danijeel** [comment]
I can confirm this issue @hobietje, it will be resolved in the upcoming release.
